name: Spread

on:
  push:
    branches:
    - main
    - staging
    - trying
    - release/[0-9]+.[0-9]+
    tags:
    - v[0-9]+[0-9]+.[0-9]+
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]

jobs:
  GetMatrix:
    runs-on: ubuntu-latest

    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}

    steps:
    - id: set-matrix
      name: Determine BuildAndTest matrix
      run: |
        set -euo pipefail

        if ${{ github.event_name == 'push' && github.ref == 'refs/heads/main' }}; then
          TASKS='"lxd:ubuntu-20.04:spread/build/ubuntu:asan"
                 "lxd:ubuntu-20.04:spread/build/ubuntu:tsan"
                 "lxd:ubuntu-20.04:spread/build/ubuntu:ubsan"
                 "lxd:ubuntu-20.04:spread/build/ubuntu:asan_clang"
                 "lxd:ubuntu-20.04:spread/build/ubuntu:tsan_clang"
                 "lxd:ubuntu-20.04:spread/build/ubuntu:ubsan_clang"'
        else
          TASKS='"lxd:alpine-3.15:spread/build/alpine:amd64"
                 "lxd:alpine-edge:spread/build/alpine:amd64"
                 "lxd:ubuntu-22.04:spread/build/sbuild:debian_sid"
                 "lxd:ubuntu-22.04:spread/build/sbuild:ubuntu"
                 "lxd:ubuntu-22.04:spread/build/sbuild:ubuntu_jammy"
                 "lxd:ubuntu-22.04:spread/build/sbuild:ubuntu_arm64"
                 "lxd:ubuntu-22.04:spread/build/sbuild:ubuntu_armhf"
                 "lxd:ubuntu-20.04:spread/build/ubuntu:rpi"
                 "lxd:ubuntu-20.04:spread/build/ubuntu:clang"
                 "lxd:fedora-35:spread/build/fedora:amd64"
                 "lxd:fedora-36:spread/build/fedora:amd64"
                 "lxd:ubuntu-22.04:spread/build/sbuild:ubuntu_devel"
                 "lxd:ubuntu-22.04:spread/build/sbuild:ubuntu_proposed"'
        fi

        echo ${TASKS:-} | jq -cs '{ "spread-task": .  }' | awk '{ print "::set-output name=matrix::" $0 }'

  BuildAndTest:
    needs: GetMatrix

    strategy:
      fail-fast: false
      matrix: ${{ fromJSON(needs.GetMatrix.outputs.matrix) }}

    runs-on: ubuntu-latest

    env:
      DEBFULLNAME: "Mir CI Bot"
      DEBEMAIL: "mir-ci-bot@canonical.com"
      SPREAD_PATH: "/tmp/spread"

    steps:
    - name: Set up LXD
      uses: whywaita/setup-lxd@v1

    - name: Set up Spread
      run: |
        curl -s -O https://people.canonical.com/~chrishr/spread.snap
        sudo snap install --dangerous spread.snap
        sudo snap connect spread:lxd lxd:lxd
        lxc profile set default security.privileged=true security.nesting=true
        sudo apt-get install --yes binfmt-support qemu-user-static
        echo "LXD_DIR=/var/snap/lxd/common/lxd" >> $GITHUB_ENV

    - name: Check out code
      uses: actions/checkout@v2

    - name: Run Spread task
      run: snap run spread -v ${{ matrix.spread-task }}
